mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.from=tranbaolong.280904@gmail.com
mail.password=oqfq kqkv gvas keix
mail.from.name=Sport Field Booking
