vnpay.tmnCode=LGY1EIV5
vnpay.hashSecret=IT5LCPZJRGC6UIEQONPAOUTFKXXQEGP6
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=https://january-sports-elevation.ngrok-free.dev/SWP391-SE2010Net-Team5/payment/vnpay-return
vnpay.ipnUrl=https://january-sports-elevation.ngrok-free.dev/SWP391-SE2010Net-Team5/payment/vnpay-ipn
vnpay.version=2.1.0
vnpay.command=pay
vnpay.orderType=other
vnpay.currCode=VND
vnpay.locale=vn
vnpay.timeZone=Asia/Ho_Chi_Minh
vnpay.expireMinutes=15
